version: '3.8'

services:
  postgres:
    image: 'postgres:15.2'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=user'
      - 'POSTGRES_DB=crediblepulseDB'
      - 'POSTGRES_PASSWORD=password'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: crediblepulseDB
      DB_USER: user
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 9090:8080
    depends_on:
      - postgres

volumes:
  postgres_data: