name: Build & Deploy Spring app

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    name: Build and Deploy Spring boot for beginner
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: crediblepulseDB
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Unit tests
        run: |
          chmod +x mvnw
          ./mvnw clean verify
          

      - name: 📦 Build Docker Images
        run: |
          chmod +x mvnw
          ./mvnw compile com.google.cloud.tools:jib-maven-plugin:3.1.4:build